name: aws configuration

on: [push]

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ sagemakermacy }}
        aws-secret-access-key: ${{ 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 }}
        aws-region: us-east-2
